# -*- coding: utf-8 -*-

"""
   DigitalNewzealandLib.Configuration

   This file was automatically generated by APIMATIC BETA v2.0 on 06/07/2016
"""

class Configuration :
    # The base Uri for API calls
    BASE_URI = "http://api.digitalnz.org"


